### ISSUE TITLE
Data Set

### ISSUE THREAD

**Issue by rmzelle** [zotero/zotero-bits#22]
There have been requests for a "Data Set" item type, but the idea is still rough.

https://github.com/ajlyon/zotero-bits/wiki/DatasetType

Related CSL schema ticket: https://github.com/citation-style-language/schema/issues/74

**Comment by pdurbin** [comment]
There's a related discussion at https://github.com/IQSS/dataverse/pull/3828#issuecomment-310395228 and I'd like to thank @adam3smith for testing Zotero with Dataverse! We'll keep an eye on this issue.

**Comment by tangofil** [comment]
I do have use for type: Dataset.  

The fields needed are well described in [http://www.dlib.org/dlib/january11/starr/01starr.html  ](http://www.dlib.org/dlib/january11/starr/01starr.html  )   

"When the DataCite Consortium was founded in 2009, the development of a DataCite metadata scheme was an early priority." The Metadata Working Group did spend a few years creating the scheme, so I think we should just use their suggestion, unless there is something newer.

Social scientists use many datasets that should be cited. Sometimes they are surveys collected in a particular location between two dates (i.e. the source does not change), sometimes they are data from public sources like Eurostat, where new data is added at regular intervals (so the source does change).

**Comment by adam3smith** [comment]
This is implemented in CSL since version 1.0.1, currently available in Zotero [using a workaround](https://www.zotero.org/support/dev/translators/datasets) and will be available in Zotero as a regular item type in the future. No need for future explanations.

**Comment by philippemiron** [comment]
Is there any info on _when_ it will be included? This issue is 10 years old.

**Comment by adam3smith** [comment]
Zotero never does ETAs, but they've been making changes to the data model, so probably not too far out (I'd guess months, but that's just a guess)

**Comment by adam3smith** [comment]
@dstillman since you're working on standard already (and it'd make a lot of people in my line of work happy if we got this into Zotero) could I advocate for including this into the next type update:

Here are the proposed field:
Name: Dataset (there are some discussion here with "Data", "Data set," "Dataset" and several other contenders, but I think Dataset makes the most sense).
- Standard fields: Title, Author/Contributor, Date, Language. Short Titel, URL, DOI, Accessed, Archive, Loc. in Archive, Library Catalog, Call Number, Rights, Extra, Data Added, Modified
- Identifier (CSL: number) -- while DOIs are very common, many repositories especially in the lifesciences have their own ID schema
- Repository and Repository Location (publisher and publisher-place respectively. The latter is getting rare, but we still see it in requested citations).
- Version
- Type (CSL: genre)
- Medium (e.g., if older Data are on CD-ROM etc.)

I've checked this against the latest iteration of the DataCite Metadata schema and it hits all relevant fields that could possibly be cited. I think it's worth keeping Archive in there for historical data that's not in a repository but in a physical archive.

**Comment by bwiernik** [comment]
Do we want to label it `Medium` or `Format` (which is what is currently used for Audio Recording, Film, Video Recording)? I don't have a strong preference for one over the other.

**Comment by adam3smith** [comment]
It's `Format` in DataCite, so if we're using that elsewhere already, let's stick with that.

**Comment by bwiernik** [comment]
Great, let's go with `Format`

**Comment by HughP** [comment]
> Do we want to label it `Medium` or `Format` (which is what is currently used for Audio Recording, Film, Video Recording)? I don't have a strong preference for one over the other.

@bwiernick Audio and Film should be cited and referenced as either film or audio units; OR collections. So `Medium` for dataset here makes sense to me. Frankly datasets should not be audio or video content. There is a difference between a dataset and a collection. People need to be citing these groups of audio and video artifacts as collections.

**Comment by adam3smith** [comment]
> Frankly datasets should not be audio or video content. There is a difference between a dataset and a collection. People need to be citing these groups of audio and video artifacts as collections.

The vast majority of people working on data and data-infrastructure would disagree with that (the are data repositories [specifically dedicated to video data](https://nyu.databrary.org/)), but that's also not the point here, so we don't need to solve it. 

The reason bwiernik mentioned that 'Format' is used for video-type item types is it is used for the format in which video content is delivered (e.g., on DVD, CD-ROM, Blueray), which is reasonably similar to the types of formats cited for data delivery (where still relevant) such as DVD, CD-ROM, so it makes sense to use the same variable. I honestly think either option would have been fine, but, as I said, aligning this with the Datacite metadata terminology probably makes sense.
